# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-17 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='muisc_list',
            new_name='music_list',
        ),
    ]
