# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-18 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20190118_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='background_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
